-- ============================================================
-- DataSpec 数据库 schema 说明
-- ============================================================
-- 本项目的数据库迁移由 Flyway 管理,迁移脚本位于:
--   src/main/resources/db/migration/V*.sql
-- 首次启动后端时 Flyway 会自动按版本顺序执行全部 V*.sql 迁移。
--
-- 如需手动初始化(例如不使用 Flyway 的场景),请按版本号顺序执行:
--   psql -U postgres -d dataspec -f db/migration/V1__init.sql
--   psql -U postgres -d dataspec -f db/migration/V2__normalize_timestamp_columns.sql
--
-- 本文件不再作为直接建表脚本,仅保留为兼容入口说明。
-- ============================================================
